---
title: "Hawaii App Notebook"
output: html_notebook
---

## Load Libraries

```{r}
# database library
library(DBI)
library(odbc)

# data library
library(tidyverse)
```

## Connect Database

```{r}
# check drivers
sort(unique(odbcListDrivers()[[1]]))
```

```{r}
# configure parameters
Driver = "MySQL ODBC 8.0 Unicode Driver"
Server = "gohawaii.cxvagtspriyp.us-east-1.rds.amazonaws.com"
UID = "admin"
PWD = "cis550-proj"
Port = 3306
Database = "Hawaii"
```

```{r}
# connect with AWS
con <- DBI::dbConnect(odbc::odbc(), 
                      Driver = Driver, 
                      Server = Server, 
                      UID = UID, 
                      PWD = PWD, 
                      Port = Port, 
                      Database = Database)
```

## Run Queries

```{r}
# query: all routes to Hawaii
airport_list <- SQL("('HNL', 'ITO', 'OGG', 'KOA', 'MKK', 'LNY', 'LIH', 'HNM', 'JHM', 'MUE')")
routes_SQL <- sqlInterpolate(con,
                             "SELECT * FROM Routes WHERE DestinationAirport IN ?list",
                             list = airport_list)
routes_SQL_data <- dbGetQuery(con, routes_SQL)
```

```{r}
# query: all airports of Hawaii
arrival_airports_SQL <- sqlInterpolate(con,
                                       "SELECT * FROM Airports WHERE IATA IN ?list",
                                       list = airport_list)
arrival_airports_SQL_data <- dbGetQuery(con, arrival_airports_SQL) 
```

```{r}
# query: all airports to Hawaii
departure_airports_SQL <- sqlInterpolate(con,
                                         "WITH r AS (SELECT * FROM Routes WHERE DestinationAirport IN ?list)
                                          SELECT * FROM Airports WHERE IATA IN (SELECT DISTINCT SourceAirport FROM r)",
                                         list = airport_list)
departure_airports_SQL_data <- dbGetQuery(con, departure_airports_SQL) 
```


```{r}
# query: all venues of Hawaii
venues_SQL <- sqlInterpolate(con, 
                             "SELECT * FROM Nearby_venues")
venues_SQL_data <- dbGetQuery(con, venues_SQL)
```

